### ISSUE TITLE
Doesn't playing nicely with redux-form

### ISSUE THREAD

**Issue by tnrich** [jasonslyvia/react-anything-sortable#56] opened 2016-07-01 18:39 UTC
Hey there,

So I'm trying to use the react-anything-sortable library with redux-form, but I am unfortunately running into issues when trying to do so. It seems that there are two potential issues at play. They can both be seen in the following screenshots where I try to drag and re-order my inserts:
1)
![image](https://cloud.githubusercontent.com/assets/2730609/16530711/47600aee-3f7e-11e6-8a56-dcdf4d12939c.png)

In the screenshot 1, I start to drag the bottom insert. It stops dragging suddenly after a redux-form/Register-Field event is fired. I believe this occurs because of how the react-anything-sortable library works. 

After I let go of the mouse, I can continue dragging, and when I try to switch inserts 2 and 3, by dropping, I get this series of redux actions:

![image](https://cloud.githubusercontent.com/assets/2730609/16530920/17df97c0-3f7f-11e6-944f-26d551f6fbf5.png)

Here is what my source code looks like: 
```js
<Sortable
              sortHandle={"taHandle"}
              onSort={function (sortedArray,previousIndex,newIndex) {
                inserts.move(previousIndex,newIndex)
              }}
              direction='vertical'
              dynamic
              >
              {
                inserts.map((insert, index) => {
                  return (
                    <SortableWrapperItem key={index} sortData={index}>
                    <Field name={insert} inserts={inserts} key={index} index={index} insertValues={insertValues} component={RenderInsert}/>
                  </SortableWrapperItem>
                )
                })
              }
            </Sortable>
```

I'm not totally sure why the Field in question is being registered/unregistered, nor why it is "moved" twice.  As I alluded to above, I think the sortable wrapper item is maybe removing its children from the dom causing redux-form to fire the unnecessary register/unregister actions and the extra move action. Is that indeed how <Sortable> works? 

It would be great if these two libraries could be made to play together nicely in some way. Any ideas as to how to remedy this would be appreciated. I've also posted this issue over at the redux-form repo as well.

Thanks!

**Comment by jasonslyvia** [comment] 2016-07-04 01:30
Sorry for the late response.

I've gone through the related issue in `redux-form`, and if it's really caused by `React.cloneElement`, I'm afraid there's nothing I can do here, because the ability to sort any children is built on the cloning premise.

Please let me know if you have further concerns.

**Comment by jasonslyvia** [comment] 2016-07-12 19:03
Closing for no further update.

**Closed by jasonslyvia** 2016-07-12 19:03 UTC
